{% set name = "morphosamplers" %}
{% set version = "0.0.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/morphosamplers-{{ version }}.tar.gz
  sha256: 82097605e42f2129445ef4ac2235430ac10d1ec6dced918bfacc58d913377f58

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - einops
    - numpy
    - psygnal
    - pydantic
    - pydantic-compat
    - python >=3.8
    - scipy
    - typing_extensions

test:
  imports:
    - morphosamplers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/morphosamplers
  summary: A library for sampling image data along morphological objects such as splines and surfaces.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/kevinyamauchi/morphosamplers

extra:
  recipe-maintainers:
    - kevinyamauchi
