{% set name = "morphosamplers" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/morphosamplers-{{ version }}.tar.gz
  sha256: 52dcfaa0e9fe75112f53cc8bc9a08307f500d5a2422f43192c1e68f6a24f9cae

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - einops
    - numpy
    - psygnal
    - pydantic <2
    - python >=3.8
    - scipy

test:
  imports:
    - morphosamplers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/morphosamplers
  summary: A library for sampling image data along morphological objects such as splines and surfaces.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/kevinyamauchi/morphosamplers

extra:
  recipe-maintainers:
    - kevinyamauchi
