{% set name = "morphosamplers" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/morphosamplers-{{ version }}.tar.gz
  sha256: a249db788daa199a5b072905fd36e61d306baf7379694a9cfc243b804f38684a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - einops
    - numpy
    - psygnal
    - pydantic
    - scipy

test:
  imports:
    - morphosamplers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/morphosamplers/
  summary: A library for sampling image data along morphological objects such as splines and surfaces.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kevinyamauchi
